tour:
  per_page: 9
  length_small: 5
  length_big: 50
book_tour:
  min_quantity: 1
  max_quantity: 49
  per_page: 6
avatar:
  size: 80
user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
    max_length: 30
